declare module "ui5/antares/entry/v2/EntryCL" {
    import { ButtonType } from "sap/m/library";
    import Control from "sap/ui/core/Control";
    import UIComponent from "sap/ui/core/UIComponent";
    import Controller from "sap/ui/core/mvc/Controller";
    import Context from "sap/ui/model/Context";
    import ModelCL from "ui5/antares/base/v2/ModelCL";
    import { DialogStrategies, FormTypes, GuidStrategies, NamingStrategies } from "ui5/antares/types/entry/enums";
    import { ISubmitResponse, IValueValidation } from "ui5/antares/types/entry/submit";
    import { ODataMethods } from "ui5/antares/types/odata/enums";
    import CustomControlCL from "ui5/antares/ui/CustomControlCL";
    import DialogCL from "ui5/antares/ui/DialogCL";
    import ResponseCL from "ui5/antares/entry/v2/ResponseCL";
    import ValueHelpCL from "ui5/antares/ui/ValueHelpCL";
    import FragmentCL from "ui5/antares/ui/FragmentCL";
    import ValidationLogicCL from "ui5/antares/ui/ValidationLogicCL";
    import { IFieldCustomData, IFormGroups, ITextInEditModeSource } from "ui5/antares/types/entry/common";
    import ObjectPageLayoutCL from "ui5/antares/ui/ObjectPageLayoutCL";
    import Target from "sap/ui/core/routing/Target";
    import Dialog from "sap/m/Dialog";
    /**
     * @namespace ui5.antares.entry.v2
     */
    export default abstract class EntryCL<EntityT extends object = object, EntityKeysT extends object = object> extends ModelCL {
        private fragmentPath?;
        private entryMethod;
        private formTitle;
        private entityPath;
        private entityName;
        private formType;
        private namingStrategy;
        private beginButtonText;
        private endButtonText;
        private beginButtonType;
        private endButtonType;
        private propertyOrder;
        private useAllProperties;
        private includeAllProperties;
        private excludedProperties;
        private mandatoryProperties;
        private readonlyProperties;
        private resourceBundlePrefix;
        private useMetadataLabels;
        private mandatoryErrorMessage;
        private selectRowMessage;
        private customControls;
        private customContents;
        private entryContext;
        private entryDialog;
        private submitCompleted?;
        private submitCompletedListener?;
        private submitFailed?;
        private submitFailedListener?;
        private valueHelps;
        private dialogStrategy;
        private containsSmartForm;
        private autoMandatoryCheck;
        private readonly tableModes;
        private uiTableModes;
        private tableId?;
        private readonly supportedTableTypes;
        private entityKeys?;
        private validationLogics;
        private displayGuidProperties;
        private generateRandomGuid;
        private formGroups;
        private defaultGroupTitle?;
        private unknownGroupTitle;
        private displayObjectPage;
        private objectPageLayout;
        private objectPageAvatarSrc;
        private objectPageHeaderLabel;
        private objectPageView;
        private fromTarget;
        private createdTarget;
        private customContentSectionTitle;
        private disableAutoClose;
        private fieldCustomData;
        private textInEditModeSource;
        constructor(controller: Controller | UIComponent, entityPath: string, method: ODataMethods, modelName?: string);
        getEntityPath(): string;
        getEntityName(): string;
        getFragmentPath(): string | undefined;
        setFragmentPath(fragmentPath: string, containsSmartForm?: boolean): void;
        getFormType(): FormTypes;
        setFormType(formType: FormTypes): void;
        getNamingStrategy(): NamingStrategies;
        setNamingStrategy(strategy: NamingStrategies): void;
        getFormTitle(): string;
        setFormTitle(title: string): void;
        getBeginButtonText(): string;
        setBeginButtonText(text: string): void;
        getEndButtonText(): string;
        setEndButtonText(text: string): void;
        getBeginButtonType(): ButtonType;
        setBeginButtonType(type: ButtonType): void;
        getEndButtonType(): ButtonType;
        setEndButtonType(type: ButtonType): void;
        getPropertyOrder(): string[];
        getUseAllProperties(): boolean;
        setPropertyOrder(order: string[], useAllProperties?: boolean): void;
        getExcludedProperties(): string[];
        setExcludedProperties(properties: string[]): void;
        getMandatoryProperties(): string[];
        setMandatoryProperties(properties: string[]): void;
        getResourceBundlePrefix(): string;
        setResourceBundlePrefix(prefix: string): void;
        getUseMetadataLabels(): boolean;
        setUseMetadataLabels(useMetadataLabels: boolean): void;
        getMandatoryErrorMessage(): string;
        setMandatoryErrorMessage(message: string): void;
        addCustomControl(control: CustomControlCL): void;
        getCustomControls(): CustomControlCL[];
        getCustomControl(propertyName: string): CustomControlCL | undefined;
        addCustomContent(content: Control): void;
        getCustomContents(): Control[];
        addValueHelp(valueHelp: ValueHelpCL): void;
        getValueHelps(): ValueHelpCL[];
        getValueHelp(propertyName: string): ValueHelpCL | undefined;
        protected setDialogStrategy(strategy: DialogStrategies): void;
        protected getDialogStrategy(): DialogStrategies;
        protected getContainsSmartForm(): boolean;
        setAutoMandatoryCheck(autoMandatoryCheck: boolean): void;
        getAutoMandatoryCheck(): boolean;
        setSelectRowMessage(message: string): void;
        getSelectRowMessage(): string;
        addValidationLogic(logic: ValidationLogicCL): void;
        getValidationLogics(): ValidationLogicCL[];
        getValidationLogic(propertyName: string): ValidationLogicCL | undefined;
        setDisplayGuidProperties(strategy: GuidStrategies): void;
        getDisplayGuidProperties(): GuidStrategies;
        setGenerateRandomGuid(strategy: GuidStrategies): void;
        getGenerateRandomGuid(): GuidStrategies;
        setReadonlyProperties(properties: string[]): void;
        getReadonlyProperties(): string[];
        setFormGroups(groups: IFormGroups[], includeAllProperties?: boolean): void;
        getFormGroups(): IFormGroups[];
        getIncludeAllProperties(): boolean;
        setDefaultGroupTitle(title: string): void;
        getDefaultGroupTitle(): string | undefined;
        setUnknownGroupTitle(title: string): void;
        getUnknownGroupTitle(): string;
        setDisplayObjectPage(display: boolean, fromTarget: string): void;
        getDisplayObjectPage(): boolean;
        setObjectPageAvatarSrc(src: string): void;
        getObjectPageAvatarSrc(): string;
        setObjectPageHeaderLabel(label: string): void;
        getObjectPageHeaderLabel(): string;
        getFromTarget(): string;
        getCreatedTarget(): Target;
        setCustomContentSectionTitle(title: string): void;
        getCustomContentSectionTitle(): string;
        getEntryMethod(): ODataMethods;
        setDisableAutoClose(disable: boolean): void;
        getDisableAutoClose(): boolean;
        setFieldCustomData(customData: IFieldCustomData[]): void;
        getFieldCustomData(): IFieldCustomData[];
        setTextInEditModeSource(textInEditModeSource: ITextInEditModeSource[]): void;
        getTextInEditModeSource(): ITextInEditModeSource[];
        addControlFromFragment(fragment: FragmentCL): Promise<void>;
        addContentFromFragment(fragment: FragmentCL): Promise<void>;
        protected addNonNullableProperties(): Promise<void>;
        attachSubmitCompleted(submitCompleted: (response: ResponseCL<EntityT>) => void, listener?: object): void;
        attachSubmitFailed(submitFailed: (response: ResponseCL<ISubmitResponse>) => void, listener: object): void;
        protected createEntryContext(data?: EntityT): void;
        getEntryContext(): Context;
        protected createEntryDialog(dialogId?: string): void;
        protected getEntryDialog(): DialogCL | FragmentCL;
        getGeneratedDialog(): Dialog;
        protected closeEntryDialog(): void;
        protected destroyEntryDialog(): void;
        closeAndDestroyEntryDialog(): void;
        valueValidation(): IValueValidation;
        private validateSmartValues;
        private validateSimpleValues;
        private checkContextMandatory;
        reset(resetAll?: boolean): void;
        submit(resetAllOnFail?: boolean): void;
        protected initializeContext(initializer: string | Context | EntityKeysT): Promise<void>;
        private setInitializer;
        private initContextFromTable;
        private tableContext;
        private uiTableContext;
        private createBindingContext;
        private getValidationLogicMethod;
        private getValidationLogicMessage;
        protected createObjectPageLayout(): void;
        getObjectPageInstance(): ObjectPageLayoutCL;
        protected createTypedView(): Promise<void>;
        protected displayTypedView(): void;
        private createNewTarget;
    }
}
